import type { Metadata } from "next";
import "@trussworks/react-uswds/lib/uswds.css";
import "@trussworks/react-uswds/lib/index.css";
import { Outfit } from "next/font/google";
import "./globals.css";
import HeaderWrapper from "@/components/general/HeaderWrapper";
import FooterWrapper from "@/components/general/FooterWrapper";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable}`}>
        <HeaderWrapper />

        {children}

        <FooterWrapper />
      </body>
    </html>
  );
}
